# Generated by Django 2.1.2 on 2018-10-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palestrante', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=160)),
                ('data', models.DateTimeField()),
                ('sala', models.CharField(max_length=50)),
            ],
        ),
    ]
