# Generated by Django 2.1.2 on 2018-10-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iftech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('M', 'Minicurso'), ('P', 'Palestra')], max_length=1)),
                ('palestrante', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=200)),
                ('data', models.DateTimeField()),
                ('sala', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Palestra',
        ),
    ]
